configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/scribo-dev%2Fscribo-fashn-ai-d2e172eb727ef7b5f945f66ecba75c69b746c2c4ec82f33528d40a03a726a042.yml
openapi_spec_hash: 6fdde60fefdb8b156df0ccf0c0d09c4f
config_hash: 8ee7f22cc5c6c2ef31e53148adb8e912
